Unable to init server: Could not connect: Connection refused
Unable to init server: 无法连接：Connection refused

(Server.py:533): Gdk-CRITICAL **: 16:54:35.249: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(Server.py:533): Gdk-CRITICAL **: 16:54:35.256: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
[I 200928 16:54:46 Server:304] 正在尝试连接到服务器...
[I 200928 16:54:47 Server:118] 连接到服务器成功: ws://47.100.88.177:2714
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
aplay: main:828: audio open error: 没有那个设备
网络连接成功.wav
[I 200928 16:54:49 Detector:69] 正在重置...
Run time of job "ICommClient.CheckAlive (trigger: interval[0:00:10], next run at: 2020-09-28 16:54:59 CST)" was missed by 0:00:04.364506
OK
[I 200928 17:06:56 Detector:76] 重置成功！
[I 200928 17:06:59 Server:208] Pinging server...
[I 200928 17:06:59 Server:184] 收到服务器消息：pong
OK
1 3.775024285697989 -0.013837505228432936
2 2.180409031212423 -0.14961254297187865
3 3.346464224608639 -0.0026133256394258292
4 1.6027501256622527 -2.0469848473394703
[I 200928 17:07:08 Detector:175] 检测到环境波动...
[I 200928 17:07:09 Server:208] Pinging server...
[I 200928 17:07:09 Server:184] 收到服务器消息：pong
OK
[I 200928 17:07:18 Detector:183] 持续检测中...
[I 200928 17:07:19 Server:208] Pinging server...
[I 200928 17:07:19 Server:184] 收到服务器消息：pong
OK
1 0.4021803071478754 -0.000625241152805801
2 0.47247392339875666 -0.3012619782649223
3 2.2077646733291085 -0.037800855369667624
4 0.5977604516056386 -0.42579727957122043
[I 200928 17:07:29 Detector:183] 持续检测中...
[I 200928 17:07:29 Server:208] Pinging server...
[I 200928 17:07:29 Server:184] 收到服务器消息：pong
OK
[I 200928 17:07:39 Server:208] Pinging server...
[I 200928 17:07:39 Server:184] 收到服务器消息：pong
1 0.6601443554436074 -4.624088842218525e-05
2 11.534529074330901 0
3 6.4917202949901345 -0.050981415544441994
4 0.8647544997820273 -3.969824892743246
[I 200928 17:07:41 Detector:183] 持续检测中...
